/* Questionnaire pré-opératoire : libellés néerlandais. Les codes des options
   restent ceux de questionnaire-schema.js ; seul l'affichage change. */
export default {
  ui: {
    stepOf: 'Stap {n} van {t}',
    next: 'Verder',
    back: 'Terug',
    send: 'Verzenden',
    sending: 'Bezig met verzenden',
    optional: 'facultatief',
    required: 'Dit antwoord is nodig om verder te gaan.',
    invalidNumber: 'Geef een getal tussen {min} en {max}.',
    invalidDate: 'Geef een geldige datum.',
    consentRequired: 'Uw akkoord is nodig om de vragenlijst te verzenden.',
    fixErrors: 'Sommige antwoorden ontbreken. Ze zijn hierboven aangeduid.',
    sendError: 'Het verzenden is niet gelukt. Controleer uw verbinding en probeer het zo meteen opnieuw.',
    tooMany: 'Te veel verzendingen vanaf deze verbinding. Probeer het over een uur opnieuw.',
    rankUp: 'Omhoog',
    rankDown: 'Omlaag',
    lensStop: 'Lenzen uit vóór het vooronderzoek: {days}.',
    lensStopDays: { 2: '48 uur', 7: 'een week' },
    lensStopFrom: 'Voor een afspraak op {date} is de laatste draagdag {last}.',
    lensWarn: 'De afspraak valt te vroeg om deze termijn te halen. Laat uw lenzen vanaf nu uit; sommige metingen moeten misschien worden herhaald.',
    doneTitle: 'Vragenlijst verzonden',
    doneThanks: 'Dank u. Uw antwoorden zijn aan Dr Sanak bezorgd om uw consultatie voor te bereiden.',
    doneRdv: 'Afspraak op {date}, locatie {site}.',
    doneLens: 'Herinnering voor uw lenzen: {days} vóór de afspraak uit.',
    doneInfo: 'Het vooronderzoek duurt ongeveer een uur. De pupillen worden tijdens het onderzoek verwijd, waardoor het zicht dichtbij twee tot drie uur wazig is: u mag na afloop niet zelf rijden.',
    addCal: 'Afspraak aan mijn agenda toevoegen',
    calTitle: 'Preoperatief vooronderzoek, Dr Sanak',
    calDesc: 'Preoperatief vooronderzoek. Ongeveer een uur. Pupilverwijding, niet zelf rijden na afloop.',
    siteLabel: 'Locatie',
  },
  sites: { delta: 'Delta', 'parc-leopold': 'Parc Léopold', cavell: 'Cavell', lambermont: 'Lambermont', nivelles: 'Nijvel' },
  steps: {
    identite: { title: 'Uw afspraak' },
    yeux: { title: 'Uw ogen in het dagelijks leven', intro: 'Geef voor elk van de vier situaties eerst aan hoe vaak dit voorkomt en daarna hoeveel hinder het geeft.' },
    sante: { title: 'Uw ogen en uw gezondheid' },
    confort: { title: 'Uw comfort in het dagelijks leven' },
    vision: { title: 'Uw zicht in het dagelijks leven', intro: 'Er bestaan verschillende manieren om het zicht te corrigeren. Deze vragen helpen om de manier te kiezen die bij uw levenswijze past. De uiteindelijke keuze gebeurt tijdens de consultatie, na onderzoek.' },
    mots: { title: 'In uw woorden' },
  },
  fields: {
    prenom: { label: 'Uw voornaam' },
    age: { label: 'Uw leeftijd', unit: 'jaar' },
    rdv: { label: 'Datum van de afspraak' },
    site: { label: 'Consultatielocatie', placeholder: 'Kies een locatie', options: { nivelles: 'Nijvel' } },

    s1_freq: { heading: 'Droogheid, een gevoel van zand of een korreltje in het oog', sub: 'Hoe vaak?', options: { 0: 'nooit', 1: 'soms', 2: 'vaak', 3: 'voortdurend' } },
    s1_sev: { sub: 'Hoeveel hinder geeft dit?', options: { 0: 'geen hinder', 1: 'draaglijke hinder', 2: 'oncomfortabele hinder', 3: 'hinderlijk', 4: 'ondraaglijke hinder' } },
    s2_freq: { heading: 'Pijn of irritatie', sub: 'Hoe vaak?', options: { 0: 'nooit', 1: 'soms', 2: 'vaak', 3: 'voortdurend' } },
    s2_sev: { sub: 'Hoeveel hinder geeft dit?', options: { 0: 'geen hinder', 1: 'draaglijke hinder', 2: 'oncomfortabele hinder', 3: 'hinderlijk', 4: 'ondraaglijke hinder' } },
    s3_freq: { heading: 'Branderig gevoel of tranende ogen', sub: 'Hoe vaak?', options: { 0: 'nooit', 1: 'soms', 2: 'vaak', 3: 'voortdurend' } },
    s3_sev: { sub: 'Hoeveel hinder geeft dit?', options: { 0: 'geen hinder', 1: 'draaglijke hinder', 2: 'oncomfortabele hinder', 3: 'hinderlijk', 4: 'ondraaglijke hinder' } },
    s4_freq: { heading: 'Vermoeide ogen', sub: 'Hoe vaak?', options: { 0: 'nooit', 1: 'soms', 2: 'vaak', 3: 'voortdurend' } },
    s4_sev: { sub: 'Hoeveel hinder geeft dit?', options: { 0: 'geen hinder', 1: 'draaglijke hinder', 2: 'oncomfortabele hinder', 3: 'hinderlijk', 4: 'ondraaglijke hinder' } },
    today: { label: 'Zijn deze klachten vandaag aanwezig?', options: { yes: 'ja', no: 'nee' } },
    duration: { label: 'Sinds hoelang?', options: { less3: 'minder dan 3 maanden', more3: 'meer dan 3 maanden' } },
    pain: { label: 'Heeft u uitgesproken oogpijn waarvoor geen oorzaak werd gevonden?', options: { yes: 'ja', no: 'nee' } },

    lenses: { label: 'Draagt u contactlenzen?', options: { yes: 'ja', no: 'nee' } },
    lens_type: { label: 'Welk type lenzen?', placeholder: 'Kies', options: { daily: 'zachte daglenzen', monthly: 'zachte maandlenzen', toric: 'zachte torische lenzen', rigid: 'harde lenzen', ortho: 'orthokeratologie (nachtlenzen)' } },
    lens_years: { label: 'Sinds hoeveel jaar?', unit: 'jaar' },
    drops: { label: 'Gebruikt u kunsttranen of oogdruppels?', options: { yes: 'ja', no: 'nee' } },
    drops_detail: { label: 'Welke en hoe vaak?' },
    allergy: { label: 'Gekende oogallergieën?', options: { yes: 'ja', no: 'nee' } },
    eye_surgery: { label: 'Heeft u ooit een oogoperatie of een oogletsel gehad?', options: { yes: 'ja', no: 'nee' } },
    eye_surgery_detail: { label: 'Licht toe' },
    family_cornea: { label: 'Heeft iemand in uw naaste familie (ouders, broers, zussen, kinderen) een hoornvliesaandoening?', help: 'Bijvoorbeeld keratoconus, een vervormd hoornvlies, harde lenzen die om die reden werden voorgeschreven, een hoornvliestransplantatie, of een laserbehandeling die werd geweigerd wegens een hoornvliesprobleem.', options: { yes: 'ja', no: 'nee', dk: 'ik weet het niet' } },
    retina: { label: 'Heeft u ooit een netvliesloslating, een netvliesscheur of een laserbehandeling van het netvlies gehad?', options: { yes: 'ja', no: 'nee' } },
    family_retina: { label: 'Heeft iemand in uw naaste familie een netvliesloslating gehad?', options: { yes: 'ja', no: 'nee', dk: 'ik weet het niet' } },
    better_without: { label: 'Ziet u zonder bril beter veraf of dichtbij?', options: { far: 'veraf', near: 'dichtbij', neither: 'geen van beide', dk: 'ik weet het niet' } },
    rx_changed: { label: 'Is uw sterkte de voorbije 12 maanden veranderd?', options: { yes: 'ja', no: 'nee', dk: 'ik weet het niet' } },
    meds: { label: 'Neemt u een van de volgende behandelingen?', options: { isotretinoin: 'isotretinoïne (Roaccutane)', antihist: 'regelmatig antihistaminica', antidep: 'antidepressiva', hormones: 'hormonale behandeling of anticonceptie', immuno: 'immunosuppressiva of cortisone', none: 'geen' } },
    conditions: { label: 'Lijdt u aan een van deze aandoeningen?', options: { autoimmune: 'auto-immuunziekte (Sjögren, reumatoïde artritis, lupus)', thyroid: 'schildklierprobleem', diabetes: 'diabetes', rosacea: 'rosacea of acne rosacea', none: 'geen' } },
    pregnancy: { label: 'Zwangerschap, borstvoeding of kinderwens binnen het jaar?', options: { yes: 'ja', no: 'nee', na: 'niet van toepassing' } },
    history: { label: 'Andere belangrijke voorgeschiedenis' },

    lens_hours: { label: 'Hoeveel uur per dag draagt u uw lenzen?', unit: 'uur' },
    lens_tol: { label: 'Verdraagt u ze goed?', options: { good: 'goed', less: 'steeds minder', bad: 'slecht' } },
    lens_evening: { label: 'Voelen uw ogen op het einde van de dag hinder van de lenzen?', options: { never: 'nooit', sometimes: 'soms', often: 'vaak' } },
    screen: { label: 'Schermtijd per dag', options: { lt2: 'minder dan 2 u', '2-5': '2 tot 5 u', '5-8': '5 tot 8 u', gt8: 'meer dan 8 u' } },
    dry_air: { label: 'Werkt u in droge lucht of met airconditioning?', options: { yes: 'ja', no: 'nee', varies: 'dat wisselt' } },
    wind: { label: 'Tranen of prikken uw ogen bij wind, kou of voor een scherm?', options: { never: 'nooit', sometimes: 'soms', often: 'vaak' } },
    sports: { label: 'Beoefent u een contactsport?', options: { combat: 'vechtsporten', rugby_football: 'rugby of voetbal', none: 'geen' } },
    dust: { label: 'Wordt u in uw werk blootgesteld aan stof of spatten?', options: { yes: 'ja', no: 'nee' } },
    work_off: { label: 'Hoeveel dagen werkonderbreking zijn denkbaar na de ingreep?', options: { '1-2': '1 tot 2 dagen', week: 'een week', more: 'meer' } },
    night_drive: { label: 'Rijdt u ’s nachts met de auto?', options: { never: 'nooit', rarely: 'zelden', regularly: 'regelmatig', often: 'vaak' } },

    priorities: { label: 'In welke situaties telt uw zicht het meest?', help: 'Rangschik van het belangrijkste naar het minst belangrijke. U kunt de regels verslepen of de pijltjes gebruiken.', options: { far: 'autorijden en buiten', mid: 'scherm, keuken, dashboard', near: 'lezen, telefoon, fijn werk' } },
    activities: { label: 'Uw activiteiten waarbij het zicht het meest telt', options: { reading: 'lezen', screen: 'scherm', golf: 'golf', tennis: 'tennis', bike: 'fietsen', shooting: 'schieten of jagen', diy: 'klussen', sewing: 'naaien', music: 'muziek van partituur', gaming: 'videogames', cinema: 'film', other: 'andere' } },
    near_time: { label: 'Tijd voor lezen of werk dichtbij per dag', options: { lt1: 'minder dan 1 u', '1-3': '1 tot 3 u', gt3: 'meer dan 3 u' } },
    night_drive_b: { label: 'Rijdt u ’s nachts met de auto?', options: { never: 'nooit', rarely: 'zelden', regularly: 'regelmatig', often: 'vaak, het is een belangrijk deel van mijn activiteit' } },
    low_light: { label: 'Moet u voor uw werk in weinig licht zien?', help: 'Chauffeur, piloot, brandweer, nachtwerk.', options: { yes: 'ja', no: 'nee' } },
    headlights: { label: 'Hoe ervaart u vandaag de koplampen ’s nachts?', options: { ok: 'zonder probleem', some: 'wat verblindend', very: 'sterk verblindend' } },
    work_env: { label: 'U werkt vooral', options: { bright: 'in een goed verlicht kantoor', dim: 'bij weinig licht', outdoor: 'buiten', varies: 'dat wisselt' } },
    progressives: { label: 'Heeft u al een multifocale bril of multifocale lenzen gedragen?', options: { ok: 'ja, zonder moeite', never_used_to: 'ja, nooit aan gewend', no: 'nee' } },
    temperament: { label: 'U herkent zich het meest in', options: { adapt: 'ik pas me snel aan een verandering aan', time: 'het duurt bij mij even', detail: 'ik merk meteen het kleinste detail op' } },
    night_vs_read: { label: 'Tussen een heel scherp nachtzicht en heel fijn lezen, wat zet u op de eerste plaats?', options: { night: 'nachtzicht', read: 'fijn lezen', dk: 'ik weet het niet' } },
    entourage: { label: 'Is iemand uit uw omgeving geopereerd? Heeft die ervaring u eerder gerustgesteld of verontrust?', options: { no: 'nee, niemand', reassured: 'ja, eerder gerustgesteld', worried: 'ja, eerder verontrust', mixed: 'ja, allebei' } },
    entourage_detail: { label: 'Enkele woorden als u wilt' },

    why: { label: 'Wat brengt u ertoe om nu deze operatie te overwegen?' },
    concerns: { label: 'Is er iets dat u bezighoudt?' },
    closing: { text: 'Deze antwoorden dienen om het gesprek voor te bereiden. De keuze van de techniek gebeurt tijdens de consultatie, na onderzoek, op basis van wat uw ogen toelaten.' },
    consent: { label: 'Ik ga ermee akkoord dat deze informatie aan Dr Sanak wordt bezorgd om mijn consultatie voor te bereiden. Ze wordt niet op deze site bewaard en wordt verwerkt volgens het <a href="/nl/privacy/">privacybeleid</a>.' },
  },
};
