/* Questionnaire pré-opératoire : libellés anglais. Les codes des options
   restent ceux de questionnaire-schema.js ; seul l'affichage change. */
export default {
  ui: {
    stepOf: 'Step {n} of {t}',
    next: 'Continue',
    back: 'Back',
    send: 'Send',
    sending: 'Sending',
    optional: 'optional',
    required: 'This answer is required to continue.',
    invalidNumber: 'Enter a number between {min} and {max}.',
    invalidDate: 'Enter a valid date.',
    consentRequired: 'Your agreement is required to send the questionnaire.',
    fixErrors: 'Some answers are missing. They are marked above.',
    sendError: 'The questionnaire could not be sent. Check your connection and try again in a moment.',
    tooMany: 'Too many submissions from this connection. Try again in an hour.',
    rankUp: 'Move up',
    rankDown: 'Move down',
    lensStop: 'Stop wearing lenses before the exam: {days}.',
    lensStopDays: { 2: '48 hours', 7: 'one week' },
    lensStopFrom: 'For an appointment on {date}, the last day of wear is {last}.',
    lensWarn: 'The appointment is too soon to allow this interval. Remove your lenses from now on; some measurements may have to be repeated.',
    doneTitle: 'Questionnaire sent',
    doneThanks: 'Thank you. Your answers have been passed on to Dr Sanak to prepare your consultation.',
    doneRdv: 'Appointment on {date}, {site} site.',
    doneLens: 'Reminder for your lenses: stop {days} before the appointment.',
    doneInfo: 'The exam takes about an hour. Your pupils are dilated during the exam, which blurs near vision for two to three hours: do not drive afterwards.',
    addCal: 'Add the appointment to my calendar',
    calTitle: 'Preoperative exam, Dr Sanak',
    calDesc: 'Preoperative exam. About one hour. Pupil dilation, no driving afterwards.',
    siteLabel: 'Site',
  },
  sites: { delta: 'Delta', 'parc-leopold': 'Parc Léopold', cavell: 'Cavell', lambermont: 'Lambermont', nivelles: 'Nivelles' },
  steps: {
    identite: { title: 'Your appointment' },
    yeux: { title: 'Your eyes day to day', intro: 'For each of the four situations, say how often it happens, then how much discomfort it causes.' },
    sante: { title: 'Your eyes and your health' },
    confort: { title: 'Your comfort day to day' },
    vision: { title: 'Your vision day to day', intro: 'There are several ways to correct eyesight. These questions help choose the one that fits the way you live. The final choice is made at the consultation, after the examination.' },
    mots: { title: 'In your words' },
  },
  fields: {
    prenom: { label: 'Your first name' },
    age: { label: 'Your age', unit: 'years' },
    rdv: { label: 'Date of the appointment' },
    site: { label: 'Consultation site', placeholder: 'Choose a site' },

    s1_freq: { heading: 'Dryness, a gritty or sandy feeling in the eye', sub: 'How often?', options: { 0: 'never', 1: 'sometimes', 2: 'often', 3: 'constantly' } },
    s1_sev: { sub: 'How much discomfort does it cause?', options: { 0: 'no discomfort', 1: 'tolerable discomfort', 2: 'uncomfortable', 3: 'bothersome', 4: 'intolerable' } },
    s2_freq: { heading: 'Pain or irritation', sub: 'How often?', options: { 0: 'never', 1: 'sometimes', 2: 'often', 3: 'constantly' } },
    s2_sev: { sub: 'How much discomfort does it cause?', options: { 0: 'no discomfort', 1: 'tolerable discomfort', 2: 'uncomfortable', 3: 'bothersome', 4: 'intolerable' } },
    s3_freq: { heading: 'Burning or watering', sub: 'How often?', options: { 0: 'never', 1: 'sometimes', 2: 'often', 3: 'constantly' } },
    s3_sev: { sub: 'How much discomfort does it cause?', options: { 0: 'no discomfort', 1: 'tolerable discomfort', 2: 'uncomfortable', 3: 'bothersome', 4: 'intolerable' } },
    s4_freq: { heading: 'Eye fatigue', sub: 'How often?', options: { 0: 'never', 1: 'sometimes', 2: 'often', 3: 'constantly' } },
    s4_sev: { sub: 'How much discomfort does it cause?', options: { 0: 'no discomfort', 1: 'tolerable discomfort', 2: 'uncomfortable', 3: 'bothersome', 4: 'intolerable' } },
    today: { label: 'Are these symptoms present today?', options: { yes: 'yes', no: 'no' } },
    duration: { label: 'For how long?', options: { less3: 'less than 3 months', more3: 'more than 3 months' } },
    pain: { label: 'Do you have marked eye pain for which no cause has been found?', options: { yes: 'yes', no: 'no' } },

    lenses: { label: 'Do you wear contact lenses?', options: { yes: 'yes', no: 'no' } },
    lens_type: { label: 'Which type of lenses?', placeholder: 'Choose', options: { daily: 'soft daily', monthly: 'soft monthly', toric: 'soft toric', rigid: 'rigid', ortho: 'orthokeratology (overnight)' } },
    lens_years: { label: 'For how many years?', unit: 'years' },
    drops: { label: 'Do you use artificial tears or eye drops?', options: { yes: 'yes', no: 'no' } },
    drops_detail: { label: 'Which ones and how often?' },
    allergy: { label: 'Known eye allergies?', options: { yes: 'yes', no: 'no' } },
    eye_surgery: { label: 'Have you ever had eye surgery or an eye injury?', options: { yes: 'yes', no: 'no' } },
    eye_surgery_detail: { label: 'Please specify' },
    family_cornea: { label: 'In your close family (parents, brothers, sisters, children), does anyone have a corneal disease?', help: 'For example keratoconus, a misshapen cornea, rigid lenses prescribed for that reason, a corneal transplant, or laser surgery declined because of a corneal problem.', options: { yes: 'yes', no: 'no', dk: 'I don’t know' } },
    retina: { label: 'Have you ever had a retinal detachment, a retinal tear or laser treatment of the retina?', options: { yes: 'yes', no: 'no' } },
    family_retina: { label: 'Has anyone in your close family had a retinal detachment?', options: { yes: 'yes', no: 'no', dk: 'I don’t know' } },
    better_without: { label: 'Without glasses, do you see better at distance or up close?', options: { far: 'at distance', near: 'up close', neither: 'neither', dk: 'I don’t know' } },
    rx_changed: { label: 'Has your correction changed in the last 12 months?', options: { yes: 'yes', no: 'no', dk: 'I don’t know' } },
    meds: { label: 'Do you take any of the following treatments?', options: { isotretinoin: 'isotretinoin (Roaccutane)', antihist: 'regular antihistamines', antidep: 'antidepressants', hormones: 'hormone treatment or contraception', immuno: 'immunosuppressants or cortisone', none: 'none' } },
    conditions: { label: 'Do you have any of these conditions?', options: { autoimmune: 'autoimmune disease (Sjögren, rheumatoid arthritis, lupus)', thyroid: 'thyroid problem', diabetes: 'diabetes', rosacea: 'rosacea or acne rosacea', none: 'none' } },
    pregnancy: { label: 'Pregnancy, breastfeeding or planning a pregnancy within the year?', options: { yes: 'yes', no: 'no', na: 'not applicable' } },
    history: { label: 'Other significant medical history' },

    lens_hours: { label: 'How many hours a day do you wear your lenses?', unit: 'hours' },
    lens_tol: { label: 'How well do you tolerate them?', options: { good: 'well', less: 'less and less', bad: 'poorly' } },
    lens_evening: { label: 'Are your eyes uncomfortable at the end of the day with the lenses?', options: { never: 'never', sometimes: 'sometimes', often: 'often' } },
    screen: { label: 'Screen time per day', options: { lt2: 'less than 2 h', '2-5': '2 to 5 h', '5-8': '5 to 8 h', gt8: 'more than 8 h' } },
    dry_air: { label: 'Do you work in dry or air-conditioned air?', options: { yes: 'yes', no: 'no', varies: 'it varies' } },
    wind: { label: 'Do your eyes water or sting in wind, cold or in front of a screen?', options: { never: 'never', sometimes: 'sometimes', often: 'often' } },
    sports: { label: 'Do you practise a contact sport?', options: { combat: 'combat sports', rugby_football: 'rugby or football', none: 'none' } },
    dust: { label: 'Does your job expose you to dust or splashes?', options: { yes: 'yes', no: 'no' } },
    work_off: { label: 'How many days off work would be workable after the procedure?', options: { '1-2': '1 to 2 days', week: 'one week', more: 'more' } },
    night_drive: { label: 'Do you drive at night?', options: { never: 'never', rarely: 'rarely', regularly: 'regularly', often: 'often' } },

    priorities: { label: 'In which situations does your eyesight matter most to you?', help: 'Rank from most to least important. You can drag the rows or use the arrows.', options: { far: 'driving and outdoors', mid: 'screen, kitchen, dashboard', near: 'reading, phone, fine work' } },
    activities: { label: 'Your activities where eyesight matters most', options: { reading: 'reading', screen: 'screen', golf: 'golf', tennis: 'tennis', bike: 'cycling', shooting: 'shooting or hunting', diy: 'DIY', sewing: 'sewing', music: 'music from a score', gaming: 'video games', cinema: 'cinema', other: 'other' } },
    near_time: { label: 'Time spent reading or working up close per day', options: { lt1: 'less than 1 h', '1-3': '1 to 3 h', gt3: 'more than 3 h' } },
    night_drive_b: { label: 'Do you drive at night?', options: { never: 'never', rarely: 'rarely', regularly: 'regularly', often: 'often, it is a major part of my activity' } },
    low_light: { label: 'Does your work require you to see in low light?', help: 'Driver, pilot, firefighter, night work.', options: { yes: 'yes', no: 'no' } },
    headlights: { label: 'How do you perceive headlights at night today?', options: { ok: 'no problem', some: 'somewhat dazzling', very: 'very dazzling' } },
    work_env: { label: 'You work mostly', options: { bright: 'in a bright office', dim: 'in low lighting', outdoor: 'outdoors', varies: 'it varies' } },
    progressives: { label: 'Have you ever worn progressive glasses or multifocal lenses?', options: { ok: 'yes, comfortably', never_used_to: 'yes, never got used to them', no: 'no' } },
    temperament: { label: 'You recognise yourself most in', options: { adapt: 'I adapt quickly to change', time: 'I take a little time', detail: 'I notice the smallest detail straight away' } },
    night_vs_read: { label: 'Between very sharp night vision and very fine reading, which would you put first?', options: { night: 'night vision', read: 'fine reading', dk: 'I don’t know' } },
    entourage: { label: 'Has someone around you had the operation? Did their experience mostly reassure or worry you?', options: { no: 'no, nobody', reassured: 'yes, mostly reassured', worried: 'yes, mostly worried', mixed: 'yes, both' } },
    entourage_detail: { label: 'A few words if you wish' },

    why: { label: 'What brings you to consider this surgery now?' },
    concerns: { label: 'Is there anything on your mind?' },
    closing: { text: 'These answers help prepare the discussion. The choice of technique is made at the consultation, after the examination, according to what your eyes allow.' },
    consent: { label: 'I agree that this information is passed on to Dr Sanak to prepare my consultation. It is not stored on this site and is processed in accordance with the <a href="/en/privacy/">privacy policy</a>.' },
  },
};
